config/routes.rb
DemoWeb::Application.routes.draw do

   root 'home#index'
   get 'registration/new' => 'registration#new', :as => :registration
   get 'login/new' => 'login#new', :as => :login
   post 'registration/create' => 'registration#create' , :as => :user_create
   post 'login/create' => 'login#create' , :as => :user_login
   get  'home/welcome/:id' => 'home#welcome' , :as => :welcome
   get  'home/welcome' => 'home#welcome' , :as => :welcome_pro
   post 'product/create' => 'product#create' , :as => :create_product
   get 'product/edit/:id' => 'product#edit' , :as => :edit_product
   post 'product/update' => 'product#update' , :as => :update_product
   get 'product/delete/:id' => 'product#delete' , :as => :delete_product
   get 'product/show' => 'product#show' 

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email


  def encrypt_password
     if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
  
  def create
    
  end

  def welcome
    @user = User.where(:id => params[:id])
    @product = Product.new
    @products = Product.all
    puts"%%%%%%%%%%%%%%%%%%%%%%#{@products.inspect}"
  end

  private

  def fact_params
    params.require(:fact).permit(:id ,:title, :content, :author,:fact_image)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
   protect_from_forgery
  def new
    @user = User.new
  end

  def create
    @user = User.new
    user = User.authenticate(params[:user][:email], params[:user][:password])
    respond_to do |format|
      if user.present?
        session[:user_id] = user.id
        format.html {flash[:notice] = 'Welcome #{user.first_name}'
        redirect_to welcome_path(user)}
        format.json {render :json => {:message => user}}
        format.xml {render :xml => {:message => user}}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => "Invalid Login ID or Password !", :status => 400 }
        format.json { render :json => 'Invalid Login ID or Password !', :status => 400 }
      end
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  protect_from_forgery
  def new
    @product = Product.new
  end
  def create
    @product = Product.create(product_params)
       respond_to do |format|
    if @product.save
        format.html {redirect_to welcome_path(session[:user_id]), :notice => "Successfully Add Product"}
        format.json {render :json => {:message => "Successfully Add Product"}}
        format.xml {render :xml => {:message => "Successfully Add Product"}}
    else
      format.html { render :action => "new" }
      format.xml  { render :xml => @product.errors.to_xml, :status => 400 }
      format.json { render :json => @product.errors.to_json, :status => 400 }
  end
    end
  end

  def edit
    @products = Product.where(:id => params[:id]).first
  end

  def update
    @products = Product.where(:id => params[:product][:id]).first
    @products.update_attributes(product_params)
    respond_to do |format|
    if @products.save
        format.html {redirect_to welcome_path(session[:user_id]), :notice => "Successfully Update Product"}
        format.json {render :json => {:message => "Successfully Update Product"}}
        format.xml {render :xml => {:message => "Successfully Update Product"}}
    else
      format.html { render :action => "new" }
      format.xml  { render :xml => @products.errors.to_xml, :status => 400 }
      format.json { render :json => @products.errors.to_json, :status => 400 }
  end
    end
  end

  def delete
    @products = Product.where(:id => params[:id]).first
    respond_to do |format|
      if @products.present?
        @products.destroy
        format.html {redirect_to welcome_path(session[:user_id]), :notice => "Successfully Deleted Product"}
        format.json {render :json => {:message => "Successfully Deleted Product"}}
        format.xml {render :xml => {:message => "Successfully Deleted Product"}}
      else
       format.html { render :action => "welcome" , :controller => "home" , :id => session[:user_id] }
      format.xml  { render :xml =>  {:message => "Product is Not Available", :status => 400 } }
      format.json { render :json =>{:message => "Product is Not Available", :status => 400 }}
      end
  end
    end

  
  def show
    @products = Product.all
    respond_to do |format|
      if @products.present?
        format.json {render :json => @products}
        format.xml {render :xml => @products}
      else
        format.xml  { render :xml => {:message => "There is no Product"} }
        format.json { render :json => {:message => "There is no Product"} }
      end
    end
  end



    private

  def product_params
    params.require(:product).permit(:id ,:name, :price)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  protect_from_forgery
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    respond_to do |format|
    if @user.save
        format.html {redirect_to root_url, :notice => "Successfully Registerd"}
        format.json {render :json => {:message => "Successfully Registerd"}}
        format.xml {render :xml => {:message => "Successfully Registerd"}}
    else
      format.html { render :action => "new" }
      format.xml  { render :xml => @user.errors.to_xml, :status => 400 }
      format.json { render :json => @user.errors.to_json, :status => 400 }
  end
    end

    end
# curl -X POST -d "user[first_name]=Yogesh&user[last_name]=Waghmare&user[email]=yogesh@gmail.com&user[password]=123&user[password_confirmation]=123" http://192.168.1.38:3000/registration/create.json
#  curl -X POST -d "user[email]=yogesh@gmail.com&user[password]=123" http://192.168.1.38:3000/login/create.json
#  curl -X POST -d "product[name]=TV&product[price]=5000" http://192.168.1.38:3000/product/create.json
#  curl -X POST -d "product[id]=3&product[name]=TV&product[price]=5000" http://192.168.1.38:3000/product/update.json
#  curl -X POST -d "product[id]=3" http://192.168.1.38:3000/product/delete/3.json
#  curl -X GET  http://192.168.1.38:3000/product/show.json
  private

  def user_params
    params.require(:user).permit(:id ,:first_name, :last_name, :email,:password_hash, :password_salt, :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<title>Paper Stack</title>
<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>
<div class="container">
	<section id="content">
		<%= form_for @user ,:as => :user, :url => user_login_path, :method => 'post'  do |f| %>
  <h1>Login Form</h1>
 <% if @user.errors.any? %>
<div class="error_messages">
<h2>Form is invalid</h2>
<ul>
<% for message in @user.errors.full_messages %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
  <%= f.text_field :email,:placeholder => "E-mail", :id => "username" %>
  <%= f.password_field :password, :placeholder => "Password", :id => "password" %>
			<div>
				<%= f.submit "Login" %>
				<%= link_to "Register", registration_path%>
			</div>
		<% end %><!-- form -->
		<%#*<div class="button">%>
			<%#*<a href="#">Download source file</a>%>
		<%#*</div><!-- button -->%>
	</section><!-- content -->
</div><!-- container -->
</body>
</html>

app/views/home/welcome.html.erb
<script type="text/javascript">
function change_rest_type(id){

var children_ids = [];


$("div.top").contents().filter(

  function(){
    if (this.nodeType == 1) { // nodeType 1 => div
      // reg exp matches div
        try {
          children_ids.push(this.id);
        } catch(e){}
    }
  }
);

// or maybe the more familiar, the non-jquery way
for(var i = 0 ; i < children_ids.length; i++){
 $("#"+children_ids[i]).hide();
}
$("#"+id).show();

}
</script>
<script type="text/javascript">


  function confirmDeleteValidate(){
var Check = confirm("You Want to delete this Fact");
if(Check){
    return true;
}else{
    return false;
}

}

</script>




  <section id="content">

<div id="wrapper">


  <div class="actions" ><span class="bus_back"><a href="javascript:void(0)" onclick="change_rest_type('add_wish')" style="font-size: 16px;
color: blue;margin-left: 83%;"> Add Fact</a></span></div>
 <div id="add_wish" style="display: none;">


<%= form_for @product, :as => :product , :url => create_product_path,:html => {:class => "input_field_div",:multipart => true } , :method => "post" do |f| %>

<div class="field_hight">
  <label>Title</label><br/>
<%= f.text_field :name, :class => "text_field_div" , :placeholder => "Product Name"%>
</div>

<%= f.hidden_field :user_id , :value => "#{session[:user_id]}" %>


<div class="field_hight">
  <label>Author</label><br/>
  <%= f.text_field :price, :class => "text_field_div" , :placeholder => "Price"%>
</div>



<div class="submit_button">
  <%= f.submit "Submit" , :class => "submit_button_tec"%>
</div>






<% end %>

 </div>



<table id="keywords" cellspacing="0" cellpadding="0" class="table_field">
        <thead>
          <tr><td colspan="4">
              <h1> Product List</h1>
            </td></tr>
          <tr align="center" class="serial" >
            <th class="headerheaderSortDown"><span>Sr No.</span></th>
            <th><span>Product Name</span></th>
            <th><span>Price</span></th>

                          <th>Actions</th>

                        </tr>


                    </thead>
                    <tbody>
                      <% if !@products.present? %>
                      <% else %>

<%@count=0%>

                      <% @products.each do |product|  %>
                      <tr class="alt" align="center">
                              <td><%=@count+= 1  %></td>
                                <td><%=product.name%></td>

                        <td ><%=product.price%></td>
                          <td ><%= link_to 'Edit', edit_product_path(product.id) %>/<%= link_to 'Delete', delete_product_path(product.id),:onclick=>" return confirmDeleteValidate();" %></td>
                                    </tr>
                               <%end%>

                                  

                        </tbody>
                </table>
<%#= will_paginate !@products %>
    <% end %>
  </section>
</div>
<script type="text/javascript">
$(function(){
  $('#keywords').tablesorter();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoWeb</title>
  <link rel="shortcut icon" href="http://d15dxvojnvxp1x.cloudfront.net/assets/favicon.ico">
  <link rel="icon" href="http://d15dxvojnvxp1x.cloudfront.net/assets/favicon.ico">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
  <style>
    table{

      padding: 20px;
      margin: 0 auto;
      width: 100%;
      height: auto;
}
table td{

  padding: 10px;
}
table th{
  padding: 10px;
background-color: lightblue;
}


  </style>
</head>
<body>
  <div class="container">
  <input name="authenticity_token"
              type="hidden"
              value="<%= form_authenticity_token %>"/>

<%= yield %>
  </div>
</body>
</html>

app/views/login/new.html.erb
<section id="content">


<%= form_for @user ,:as => :user, :url => user_login_path, :method => 'post'  do |f| %>
  <h1>Login Form</h1>
 <% if @user.errors.any? %>
<div class="error_messages">
<h2>Form is invalid</h2>
<ul>
<% for message in @user.errors.full_messages %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
  <%= f.text_field :email, :placeholder => "E-mail" %>
  <%= f.password_field :password , :placeholder => "Password"%>
  <%= f.submit "Login" %>

<% end %>
  <%= link_to "Register", registration_path%>
</section>

app/views/product/edit.html.erb
  <section id="content">
<%= form_for @products, :as => :product , :url => update_product_path,:id => @products.id, :method => "post" do |f| %>
<h1>Edit Product</h1>

<div class="field_hight">
  <label>Product Name</label><br/>
<%= f.text_field :name, :class => "text_field_div" %>
</div>
<%= f.hidden_field :id , :value => "#{@products.id}" %>
  <div class="field_hight">
  <label>Price</label><br/>
  <%= f.text_field :price, :class => "text_field_div" %>
</div>



<div class="submit_button">
  <%= f.submit "Submit" , :class => "submit_button_tec"%>
</div>





<% end %>
  </section>

app/views/product/new.html.erb
<script type="text/javascript">
function change_rest_type(id){

var children_ids = [];


$("div.top").contents().filter(

  function(){
    if (this.nodeType == 1) { // nodeType 1 => div
      // reg exp matches div
        try {
          children_ids.push(this.id);
        } catch(e){}
    }
  }
);

// or maybe the more familiar, the non-jquery way
for(var i = 0 ; i < children_ids.length; i++){
 $("#"+children_ids[i]).hide();
}
$("#"+id).show();

}
</script>
<script type="text/javascript">


  function confirmDeleteValidate(){
var Check = confirm("You Want to delete this Fact");
if(Check){
    return true;
}else{
    return false;
}

}

</script>





<div id="wrapper">


  <div class="actions" ><span class="bus_back"><a href="javascript:void(0)" onclick="change_rest_type('add_wish')" style="font-size: 16px;
color: gray;"> Add Fact</a></span></div>
 <div id="add_wish" style="display: none;">


<%= form_for @product, :as => :product , :url => create_product_path,:html => {:class => "input_field_div",:multipart => true } , :method => "post" do |f| %>

<div class="field_hight">
  <label>Title</label><br/>
<%= f.text_field :title, :class => "text_field_div" %>
</div>




<div class="field_hight">
  <label>Author</label><br/>
  <%= f.text_field :author, :class => "text_field_div" %>
</div>

   <div class="field_hight">
  <label>Author</label><br/>
  <%= f.file_field :fact_image, :class => "text_field_div" %>
</div>

   <div class="field_hight">
  <label>Content</label><br/>
  <%= f.text_area :content,:class => "text_area_div" %>

</div>


<div class="submit_button">
  <%= f.submit "Submit" , :class => "submit_button_tec"%>
</div>






<% end %>

 </div>

  <h1 style="font-size:18px;">List of Facts</h1>

<table id="keywords" cellspacing="0" cellpadding="0" class="table_field">
        <thead>
          <tr align="center" class="serial" >
            <th class="headerheaderSortDown"><span>Sr No.</span></th>
            <th><span>Fact Image</span></th>
            <th><span>Title</span></th>

            <th><span>Content</span></th>
            <th><span>Author</span></th>

                            <th>Actions</th>

                        </tr>


                    </thead>
                    <tbody>
<%@count=0%>

                      <% @fact.each do |fact|  %>
                      <tr class="alt" align="center">
                              <td><%=@count+= 1  %></td>
                              <td><%= image_tag fact.fact_image.url(:thumb) ,:size => "50x50"%></td>
                                  <td><%=fact.title%></td>

                        <td ><%=fact.content%></td>
                        <td ><%=fact.author%></td>

                        <td ><%= link_to 'Edit', edit_path(fact.id) %>/<%= link_to 'Delete', delete_path(fact.id),:onclick=>" return confirmDeleteValidate();" %></td>
                                    </tr>
                               <%end%>

                        </tbody>
                </table>
<%= will_paginate @fact %>
</div>
<script type="text/javascript">
$(function(){
  $('#keywords').tablesorter();
});
</script>